### ISSUE TITLE
how to construct metadata.tsv for paired-end data

### ISSUE THREAD

**Issue by KunFang93** [zhxiaokang/RASflow#12]
Hi, 

I was wondering how could I construct metadata.ts for paired_end data? For example, if I have Untreated sample 1,2 and treated sample 3,4. from 4 mice. Could I write metadata.tsv in this way:
sample group subject
S1_R1 untreated 1
S1_R2 untreated 1
S2_R1 untreated 2
S2_R2 untreated 2
S3_R1 treated 3
S3_R2 treated 3
S4_R1 treated 4
S4_R2 treated 4

Thanks!
Kun

**Comment by KunFang93** [comment]
Hi, Xiaokang

Thanks for your reply~ I will try your suggestion. I also noticed that in your tutorial file, you said the metadata.tsv has only two cols: sample and group. But in your example metadata.tsv, it has three cols: sample/group/subject. I was wondering if the subject column could be ignored? Thanks!

Best,
Kun

**Comment by KunFang93** [comment]
Hi, Xiaokang
If I three biological replicate samples for the control group and three biological replicate samples for the treatment (both of them are pair end), I was wondering if I can write in this way?
sample  group   subject
wt_nl_1 Control 1
wt_nl_2 Control 2
wt_nl_3 Control 3
wt_ll_1 Treatment       4
wt_ll_2 Treatment       5
wt_ll_3 Treatment       6
Thanks!

Best,
Kun

**Comment by zhxiaokang** [comment]
The description of the metafile in Tutorial is a mistake. Thank you for pointing this out! It's now [fixed](https://github.com/zhxiaokang/RASflow/commit/9918e5846c838cca06dc1288fd5bb138a90b54b3).

It's correct what you wrote there. Just to make sure: based on your sample ID, I guess that the FASTQ files of sample`wt_nl_1` are named like `wt_nl_1_*R1*.f*q.gz,  wt_nl_1_*R2*.f*q.gz`, and the same pattern for the other 5 samples. 

Since you're giving 6 different numbers in the 3rd column, I suppose that you're not going to do paired-test in DEA. Then you can just leave it blank. But anyway, as long as you set the following parameter in config file config_main.yaml to `FALSE`, the 3rd column will be ignored:
```
## Is your experiment designed in a pair-wise way?
PAIR: FALSE  # Is this a pair test or not? ("TRUE" or "FALSE")
```

**Comment by KunFang93** [comment]
Thanks for your prompt reply! You are welcome~ Understand, I will try to set the parameter in the config_main.yaml file.
