### ISSUE TITLE
How can I change default FDR treshold in DEA module?

### ISSUE THREAD

**Issue by daalopezgo** [zhxiaokang/RASflow#20]
Hi!

I am wondering if it is possible to change the default FDR value set for DEA which is 0.05. I would like to check if setting a higher threshold gives interesting results. I checked the corresponding rules file but it doesn't seem to include the value.

Please help! Many thanks :)

**Comment by zhxiaokang** [comment]
Hi, 

The DEG list is simply a sub-list of the whole DEA list by cutting the FDR, so you can always go to DEA list and cut the list with any threshold you like. But to make it more straightforward, I've updated the code so that you can set the threshold of FDR in the config file (configs/config_main.yaml : FDR): [new commit: make FDR configurable](https://github.com/zhxiaokang/RASflow/commit/fa41bdd5b0670e20ae37e8ff04e35184169f106f) 

Please update the source code with `git pull` or download the latest version of RASflow.

With that, I'll close this issue.
