### ISSUE TITLE
Show top 50 or 100 genes on heatmap

### ISSUE THREAD

**Issue by Ben7124** [zhxiaokang/RASflow#29]
Hello,

I notice the heatmap only shows the top 20 differentially expressed genes. Is there any way to change this to top 50 or 100 DEGs?
Thank you.

**Comment by zhxiaokang** [comment]
Hi,

You can change the number of DEGs to be shown in heatmap in line 140 in the script `scripts/visualize.R`. But since more genes are shown in the figure, the settings of the figure especially the size may also need to be adjusted in lines 152~155.

And one trick for you: every time you make a change in the script and want to test it (how the new figure looks like), you need to delete the output file (the heatmap pdf file), and then just re-run `python main.py`. RASflow will skip everything else and only re-run the visualization step.

Let me know if you have more questions.

**Comment by zhxiaokang** [comment]
Hi @Ben7124 , I'll close it now. Feel free to reopen it if you have further questions on this issue.
