### ISSUE TITLE
Issue with visualization

### ISSUE THREAD

**Issue by conlank** [zhxiaokang/RASflow#3]
I am getting an error with the visualization step.

`Querying chunk 56

Finished

Pass returnall=TRUE to return lists of duplicate or missing query terms.

Error in '$<-.data.frame'('*tmp*', "lab", value = c("Lcn2", "Cd24a", "Sprr1a",  : 
  replacement has 55422 rows, data has 55421

Calls: plot.volcano.heatmap -> EnhancedVolcano -> $<- -> $<-.data.frame

Execution halted
`

I am also getting the warning
`Loading required package: ggrepel

Warning message:

In readLines(con) :

  incomplete final line found on 'configs/config_main.yaml'

Querying chunk 1

Querying chunk 2

`

Any help with these? Am I missing a package in R? 
I also noticed it's not possible to use the main.py to run just the visualization without redoing the DEA, running it with DEA set to returns
`Which mapping reference will be used?
 genome
Is DEA requred?
 False
Is visualization requred?
 True
Please double check the information above
Do you want to continue? (y/n)
y
Start RASflow on project: project
Trimming is not required
Start mapping using  genome  as reference!
Building DAG of jobs...
Nothing to be done.
`

**Comment by zhxiaokang** [comment]
Thank you for reporting! 

About your question of "it's not possible to use the main.py to run just the visualization without redoing the DEA", it's more about the logic behind the workflow: visualization is to visualize results of DEA, so visualization cannot happen without finishing DEA. So if you want to do visualization, DEA has to be set "yes". But if you have already finished DEA, and now only want to do visualization, no worry about "redoing" the DEA, because when Snakemake finds that the output files of DEA are already there, it will skip DEA.

About the errors, missing a package won't be the reason. Because once you set up the environment with env.yaml, all required packages are installed. 

For "incomplete final line" in yaml file, I would guess that when you modified config_main.yaml, you accidentally removed some lines. Try adding an empty line in the end of the file.

For the error from volcano plot, it seems that there's something wrong in the dea table. Could you double check the dea* tables to make sure that they're alright? If you still get errors, is it OK to share the normalized count tables and dea tables with me? I need the data to debug, because I've never seen that error from my data.

**Comment by zhxiaokang** [comment]
The issue seems solved. I'll close it. But don't hesitate to comment below if there's any further problem.
