### ISSUE TITLE
raw counts

### ISSUE THREAD

**Issue by MusculusMus** [zhxiaokang/RASflow#36]
I ran the RASflow in a docker container and got all the results.  The RASflow is helpful to do RNAseq analysis automatically.

I need to find the raw counts in integer numbers.  Nor `gene_abundance.tsv` nor `gene_norm.tsv` has integer numbers. After searching all the files in the `output` dir, in the subfolder, I found `aux_info/ambig_info.tsv`, which contains two columns: `UniqueCount` and	`AmbigCount`.  Are they the source of all the values in the tsv files?  what's the actual meaning of `UniqueCount` and	`AmbigCount`?

**Comment by zhxiaokang** [comment]
From the file names, I can see that you mapped the reads to transcriptome. In that pipeline, [Salmon](https://combine-lab.github.io/salmon/) is used to estimate the abundance of transcripts and then [tximport](https://f1000research.com/articles/4-1521/v2) is used to obtain the gene abundance from its relevant transcripts. In that case, as `Salmon` puts on its website "Don't count . . . quantify!" it produces estimation instead of real count.

If you want to get the genes' read counts, I suggest to go for the other pipeline "genome" as shown in the[workflowchart](https://github.com/zhxiaokang/RASflow/blob/master/workflow/workflow_chart.jpg)

**Comment by MusculusMus** [comment]
Thanks for your reply. I will try the `genome` option. You can close the issue then.

**Comment by zhxiaokang** [comment]
Will close it for now. Don't hesitate to reopen it if you encounter further issues on the `genome` pipeline.
