### ISSUE TITLE
Merging fastq files prior to salmon quantification 

### ISSUE THREAD

**Issue by moelzek** [zhxiaokang/RASflow#4]
As part of my pipeline, I want to merge files based on groups in the config file prior to run on salmon. Is there an easy way to do this. My understanding of the wildcards of snakemake is very rudimentary. Thanks so much in advance!

**Comment by zhxiaokang** [comment]
But as I understand, Salmon takes the fastq files as input, which is one or two files (single/pair) for each sample. So I don't see the point of merging files based on groups prior to salmon. I would suggest using quantify_trans.rules to run Salmon, and then use the rule "combineSamples" in dea_trans.rules to merge samples into groups.

**Comment by moelzek** [comment]
This is mainly to go around processing a sample run in multiple lanes separately. Salmon combines input files into one search. I could manually concatenate these files before running into the pipeline. However, I would prefer a more streamlined option.

**Comment by zhxiaokang** [comment]
Sorry, but I can't clearly get your point. Do you mean you don't want to split processing one sample into multiple threads? If that's the problem, simply set the parameter -p to 1. The wildcard "sample" will go through all the values of "sample", and it's sequential instead of parallel, so the samples will be processed one after one. Does that answer your question? If not, I think I need a more detailed description of your problem so that I can better understand the issue and help you

**Comment by zhxiaokang** [comment]
I'll close the issue for now. Don't hesitate to reopen it whenever needed.
