### ISSUE TITLE
Error with mapping to genome

### ISSUE THREAD

**Issue by yashondhi** [zhxiaokang/RASflow#7]

**Comment by yashondhi** [comment]
Hi,
I was able to use the scripts for cleaning and trimming and it runs on sample data. 
When I use it on my data however, this error occurs 

[Mon Mar 23 18:39:33 2020]
Error in rule indexGenome:
    jobid: 19
    output: data/output/test_23_march/moth/genome/indexes, data/output/test_23_march/moth/genome/splicesites.txt

RuleException:
CalledProcessError in line 52 of /ufrc/kawahara/yashsondhi/rnaseq/test_analysis_ver1_2018-10-17/Workflow/snakemake_rnaseq/RASflow/workflow/align_count_genome.rules:
Command ' set -euo pipefail;  mkdir data/output/test_23_march/moth/genome/indexes && hisat2-build -p 28 data/example_self/ref/genome/Bombyx_mori.ASM15162v1.dna_rm.toplevel.fa data/output/test_23_march/moth/genome/indexes/index&& hisat2_extract_splice_sites.py data/example_self/ref/annotation/Bombyx_mori.ASM15162v1.gene.gtf > data/output/test_23_march/moth/genome/splicesites.txt ' returned non-zero exit status 137.
  File "/ufrc/kawahara/yashsondhi/rnaseq/test_analysis_ver1_2018-10-17/Workflow/snakemake_rnaseq/RASflow/workflow/align_count_genome.rules", line 52, in __rule_indexGenome
  File "/home/yashsondhi/.conda/envs/rasflow/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job indexGenome since they might be corrupted:
data/output/test_23_march/moth/genome/indexes
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /ufrc/kawahara/yashsondhi/rnaseq/test_analysis_ver1_2018-10-17/Workflow/snakemake_rnaseq/RASflow/.snakemake/log/2020-03-23T183814.282020.snakemake.log

**Comment by zhxiaokang** [comment]
Hi, the error says that the problem lies in line 52, which is `hisat2_extract_splice_sites.py {config[ANNOTATION]} > {output.splicesites}`. 

So I would guess that it's the problem with the annotation file (`data/example_self/ref/annotation/Bombyx_mori.ASM15162v1.gene.gtf` in your case). 

Double check the gtf file (for example compare it with the example data to see whether they have the same format). 

If the file is all right, then try to manually run the command `hisat2_extract_splice_sites.py data/example_self/ref/annotation/Bombyx_mori.ASM15162v1.gene.gtf > temp.splicesites.txt` and see whether that can give some more informative errors

**Comment by yashondhi** [comment]
It works fine, it was just an issue with memory and file size.
